# Exercise 1 : Array Creation and Manipulation

In [3]:
import numpy as np
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array1)

[0 1 2 3 4 5 6 7 8 9]


# Exercise 2 : Type Conversion and Array Operations

In [4]:
#Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.
float_list = [3.14, 2.17, 0, 1, 2]
float_array = np.array(float_list)
int_array = float_array.astype(int)
print(int_array)

[3 2 0 1 2]


# Exercise 3 : Working with Multi-Dimensional Arrays

In [ ]:
#Create a 3x3 NumPy array with values ranging from 1 to 9.
array_3x3 = np.arange(1, 10).reshape(3, 3)# 2d array with 3 rows and 3 columns
print(array_3x3)
# or 
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

In [ ]:

random_array = np.random.rand(4, 5)
print(random_array)

[[0.01759031 0.32578452 0.63844269 0.19617142 0.49526553]
 [0.25964407 0.19571547 0.97214303 0.3983109  0.68587463]
 [0.63266242 0.29399381 0.44023656 0.73614149 0.65606322]
 [0.69186435 0.33943293 0.7334709  0.17918785 0.8264955 ]]


# Exercise 5 : Indexing Arrays

In [ ]:

array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
second_row = array[1]
print(second_row)


[20 21 22 23 24]


# Exercise 6 : Reversing elements

In [12]:

array = np.array([0,1,2,3,4,5,6,7,8,9])
reversed_array = array[::-1]
print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]


#  Exercise 7 : Identity Matrix


In [ ]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Exercise 8 : Simple Aggregate Funcs

In [ ]:

array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
sum_array = np.sum(array)
avg_array = np.mean(array)
print(f"Sum: {sum_array}, Average: {avg_array}")

Sum: 45, Average: 4.5


# Exercise 9 : Create Array and Change its Structure

In [17]:
array = np.arange(1, 21).reshape(4, 5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# Exercise 10 : Conditional Selection of Values

In [ ]:
array = np.arange(1, 10)
odd_numbers = array[array % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]
